### ISSUE TITLE
Can't launch game, "GAME doesn't have valid launch options. Is Proton Enabled?"

### ISSUE THREAD

**Issue by duarm** [Rosentti/opensteamclient#15]
trying to run deep rock galactic, this error occurs, even tho proton seems enabled in the options. 
It's also set in the global options to Proton Experimental, and the client was restarted. I'm on 90a6d1b
![image](https://github.com/20PercentRendered/opensteamclient/assets/26150581/0cc091ce-ee48-47f9-ba20-bd13347ccd00)

![image](https://github.com/20PercentRendered/opensteamclient/assets/26150581/9fc45eed-8fca-4a65-8adc-4a1ccfb0b227)

**Comment by 20PercentRendered** [comment]
Do you have updates enabled? Sometimes it can take some time for those settings to apply due to it loading.

**Comment by duarm** [comment]
don't think there's any updates on going, I've waited a long time already. The update screen was working when I first opened, but it stopped working since, it's empty, despita having a "1 update" at the bottom

![image](https://github.com/20PercentRendered/opensteamclient/assets/26150581/4f26e7ee-0db4-4fba-8bfb-8a81e5f01e72)

**Comment by 20PercentRendered** [comment]
If you have the mobile app on your phone, try finding DRG in your library there and seeing if there's an update through remote download.

**Comment by duarm** [comment]
I've just quitted and restored valve steam, there's no update for drg there, the console prints this
```
[App 548430] 0: Didn't match linux filter and proton is disabled
[App 548430] 1: Didn't match linux filter and proton is disabled
[App 548430] 2: Didn't match linux filter and proton is disabled
[App 548430] 3: Didn't match linux filter and proton is disabled
[App 548430] 4: Didn't match linux filter and proton is disabled
```

**Comment by hurricane-dorian** [comment]
I'm having the same issue.
Seems to me that opensteam installs proton as just another app in $%APPDATA while Steam installs it in .steam/root/compatibilitytools.d

**Comment by Rosentti** [comment]
Could it be that we don't have installscript support? We'd need to figure out how regular steam finalizes updates, or if it calls some APIs. Though it seems like it'd be handled by steamservice, which makes things difficult.
 
> Seems to me that opensteam installs proton as just another app in $%APPDATA while Steam installs it in .steam/root/compatibilitytools.d

Steam does it this way for me though. You could always try installing Proton GE or other custom Proton into OpenSteam's compatibilitytools.d and seeing if it collaborates better with that.

**Comment by Rosentti** [comment]
Also check that you have steamserviced running when attempting to play proton games. It's needed.
