### ISSUE TITLE
Can this client rechecks/verify existing files before downloading?

### ISSUE THREAD

**Issue by awsms** [Rosentti/opensteamclient#25]
I tried with a bunch of already installed games, and for each of them opensteamclient deleted all the existing files, then re-dl them

**Comment by awsms** [comment]
Well if someone else was wondering, you have to close and relaunch the client once you add a library folder. Otherwise it'll delete and re-download everything :ghost:

**Comment by Rosentti** [comment]
Huh. That is interesting. I was also wondering this at some point. This means we might need to import some data from ValveSteam's install folder (I know libraryfolders.vdf keeps important data, maybe copying that will do?).
