### ISSUE TITLE
Sorting / UI / Login

### ISSUE THREAD

**Issue by nPHYN1T3** [Rosentti/opensteamclient#32]
Sorry if this has been asked (I couldn't find any mention but search terms can vary so much...) but my library is flooded with hundreds of "things" and I was wondering if there was a way to filter just what is installed?

There is a little search input above the list in library view and a button? beside that with no label. I click on that and check Installed under App State but it doesn't work. The App Type filters some things but not completely or correctly.

* Did some digging this filter might work but opensteam doesn't link to the library correctly. Even when I manually add the library directory it still doesn't work i.e. can't launch anything either.

I also noticed most the menu entries at the top (view friends etc) have no entries if clicked on. I get it if it's not implemented but normally you'd "gray" them if that was the case or at least have a place holder menu entry that just says not implemented yet. (lots of text is cut off too Insta, Enable compatibility for t, please be patient as th, with a beta ke, heck cod) 

Another odd thing was it seemed to import one single solitary category but not the others.

Lastly logging in for the first time after inputting the security code from email you can't progress. You have to cancel everything and restart. Perhaps that should be noted in the UI until it's fixed?

**Comment by Rosentti** [comment]
Hi. There's lots of issues with the Qt/C++ version. This issue is due to us using app tags, as it's the closest thing to categories I could find. However, it turns out app tags were left unused after the new library ui update, and instead valve made yet another system for storing all the new library data. The C# version handles the library data correctly (no library GUI yet though). And the login is also much improved in that version.

**Comment by Rosentti** [comment]
As for filters, the new library will support dynamic collections, which is also what ValveSteam uses for it's search.

**Comment by nPHYN1T3** [comment]
When will the C# build be buildable?

**Comment by Rosentti** [comment]
When the pull request gets merged it'll be as workable as the old Qt based one at minimum (but with broken features actually working). Then I'll add in other important features.

**Comment by nPHYN1T3** [comment]
Hey I just noticed you wanted a better logo. I do A/V work so if you toss me a general idea I could mock some things up. Also if you need dings, boops, and buzzers for audio cues in the UI toss me a list and I'll make them.

**Comment by Rosentti** [comment]
Sounds cool. I like the general design of the current one where it mimics steam's logo, but we should color it red and make it not be of a copyright similarity. The piston would need to change somewhat for that reason, maybe just a solid white fill or something? I quite like the color red and will eventually also build an Avalonia theme for the app around it (for now it just uses Avalonia defaults, which do look great, but are rather generic looking)

As for the sounds? Maybe when I add something similar to Steam's big picture mode or just a "controller mode" for the main UI (this is pretty low on the priority list though, might take a couple years or so to get here)

Currently I'm focusing on getting the library done, then some sort of way to host HTML pages inside the client to use for store and community pages (which disable when launching a game, unlike steam where they stay a resource hog...).
Then the bulk of the dev effort for getting it workable should be over, with just adding minor things like a settings page.

Then I can start with all the fun and new stuff like friends lists, concommand console and big picture mode/controller support.

**Comment by nPHYN1T3** [comment]
Heh I was bored earlier so I whipped up a few things. Just a couple of things, Error, Uh-Oh, Attention, Launch, Download Complete (kinda cornball heh)
[Open-Steam-Sounds.zip](https://github.com/Rosentti/opensteamclient/files/12811552/Open-Steam-Sounds.zip)

I'll give the logo a think. I had an idea earlier but I'm unsure if I can get it clean and readable but I'll see what I can come up with.

**Comment by nPHYN1T3** [comment]
So you want flat single color, but something that doesn't brush against trade infringement but like the current one that could be trade infringement heh. The only idea I had like that (so far) was a piston, no steam, no lever arms. Sounds like either way you just want the current one made more exactly.
![orig-clean](https://github.com/Rosentti/opensteamclient/assets/38122105/796a8d59-10f3-4fce-824e-613a94643ce0)

**Comment by Rosentti** [comment]
I quite fancy the gradient. The piston could also be replaced with something else steam engine related (ideally something that would fit into the logo, but it could also be the piston but just ending abruptly (so that it looks like it extends beyond the background circle)

**Comment by nPHYN1T3** [comment]
For now I've just cleaned up the original with in circle and "breakout" styles in white and black. I'll try the piston in a bit but in the end it will be in the repo and you can just use what you want. Check out the big picture audio and let me know if there are any other audio cues you need.

**Comment by Rosentti** [comment]
That piston design is gorgeous, that could definitely be the new logo. Can't review the new sounds yet but will soon. The original sounds you made sounded great as well though. 
Is it ok if take that iteration of it and use it in the README and app (in the C# branch)?

**Comment by nPHYN1T3** [comment]
Go ahead, I set the license to MIT so it's compatible.

**Comment by Rosentti** [comment]
Brilliant, will add the logo in the next commit.
Also, brilliant big picture entering jingle. I have audacity installed so I can cut silences out if needs be.
Will also credit you in the README and app credits, and when I eventually decide to make a Discord server I'll give you a "Logo Designer" and "Sound designer" role there if you want to.

**Comment by nPHYN1T3** [comment]
The audio is trimmed as tight as it goes. I'm an audio engineer so you won't need to touch that. I just added a header version.

**Comment by Rosentti** [comment]
There's no fonts chosen yet, but if you want to you can also find a good free to use font. Also, yeah guess that audio bit makes sense, you don't want it abruptly ending, just that I couldn't hear anything towards the end.

**Comment by nPHYN1T3** [comment]
Most people probably won't hear the tail. I'm in a studio and even with my engineering monitors it's still best to just watch the meters. I may fool a bit later on. Free/Open is already tricky for me in the font world. I've got like 10K installed but few are open heh.

**Comment by Rosentti** [comment]
Hmm, Some sans font should be good enough for now until typefaces and design language is decided. If you want to, you could make banners for OpenSteamworks.Client and OpenSteamworks as well (First one is a C# library which allows you to make your own steam client UI's and general client behaviour like logging in, and OpenSteamworks is just a simple wrapper over the native APIs provided by steamclient.dll which is aimed at making tools which make use of Steam's Client APIs like external compat tool managers)

**Comment by nPHYN1T3** [comment]
I just updated the header version with a nice open font ;) (TASA) It's not 100% what I'd go for but it works.

**Comment by Rosentti** [comment]
I assume the header svg isn't supposed to cut off?
![image](https://github.com/Rosentti/opensteamclient/assets/32398752/2c71806e-aeb0-4f3c-b747-bddfcbf098c0)

Hmm, and I'm planning to eventually split this into three repos:
- this repo, OpenSteamClient (has ClientUI and ClientConsole)
  - Would be the main repo for non developers, description: "Community-made Steam Client alternative"
- OpenSteamworks (has OpenSteamworks)
  - Description: "Library for interfacing with a running Steam Client"
- OpenSteamworks.Client (has OpenSteamworks.Client)
  - Description: "Library for creating your own Steam Client"

**Comment by nPHYN1T3** [comment]
What are you viewing the svg with? Remember it's SVG, if you don't have the right fonts installed (which it looks like you don't) it won't render correctly, hence why I added png renders.

**Comment by Rosentti** [comment]
Ah, that makes sense. Will use the renders in the README then.
Oh, and I quite like [Nitrox](https://github.com/SubnauticaNitrox/Nitrox)'s style of banner, ignoring the fact that it's a gif (Icon, name, description, fancy background). But we could also do something like
![image](https://github.com/Rosentti/opensteamclient/assets/32398752/b8479e26-0582-49ad-9cd9-2c31ce30daad)
(quick mockup of the layout only, GH doesn't like max-width and max-height tags)
```html
<table style="width:100%; border:1px solid black;">
  <tr>
    <td><img style="max-width:80px; max-height:80px;" src="https://raw.githubusercontent.com/nPHYN1T3/opensteamclient-AV-Assets/main/icons/logo3-piston-white.svg" alt="Logo"/></td>
    <td><p>
    <b>OpenSteamClient</b> <br>
    A community-made, open-source Steam client.
    </p></td>
  </tr>
</table>
```

Though we at the moment don't have any images to show for the background so let's just use the gradient, but maybe darker red or a black/gray gradient.

**Comment by nPHYN1T3** [comment]
This could become a huge discussion heh. Format and application can get insane. Print vs web, accessibility, design choices vs possible user choices (light/dark webpage eats like images).

**Comment by Rosentti** [comment]
Yep. Though having the project name and description as text should help accessibility, and using a plain old table should make light/dark work well.

**Comment by nPHYN1T3** [comment]
Well that's what alt/text tag in the html is for ;)
